[2024-04-19T02:29:03.728+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MLOP_pro.download_file_task manual__2024-04-19T02:29:01.285430+00:00 [queued]>
[2024-04-19T02:29:03.735+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MLOP_pro.download_file_task manual__2024-04-19T02:29:01.285430+00:00 [queued]>
[2024-04-19T02:29:03.735+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-04-19T02:29:03.744+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_file_task> on 2024-04-19 02:29:01.285430+00:00
[2024-04-19T02:29:03.762+0000] {standard_task_runner.py:57} INFO - Started process 336 to run task
[2024-04-19T02:29:03.771+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'MLOP_pro', 'download_file_task', 'manual__2024-04-19T02:29:01.285430+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmpk8o4ry5_']
[2024-04-19T02:29:03.781+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask download_file_task
[2024-04-19T02:29:03.891+0000] {task_command.py:416} INFO - Running <TaskInstance: MLOP_pro.download_file_task manual__2024-04-19T02:29:01.285430+00:00 [running]> on host d35862d43e4d
[2024-04-19T02:29:03.944+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Group_9' AIRFLOW_CTX_DAG_ID='MLOP_pro' AIRFLOW_CTX_TASK_ID='download_file_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-19T02:29:01.285430+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-19T02:29:01.285430+00:00'
[2024-04-19T02:29:22.497+0000] {logging_mixin.py:154} INFO - your file from <Response [200]> is downloading please wait for 100 secs.
[2024-04-19T02:29:22.501+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/download_new.py", line 26, in download_file
    with open(zipfile_path, "wb") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/Online_Retail_II.zip'
[2024-04-19T02:29:22.516+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=MLOP_pro, task_id=download_file_task, execution_date=20240419T022901, start_date=20240419T022903, end_date=20240419T022922
[2024-04-19T02:29:22.529+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task download_file_task ([Errno 2] No such file or directory: '/opt/airflow/dags/data/Online_Retail_II.zip'; 336)
[2024-04-19T02:29:22.584+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-19T02:29:22.603+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
